### ISSUE TITLE
incorrect tip labels produced by smc2arg 

### ISSUE THREAD

**Issue by hyanwong** [mdrasmus/argweaver#20]
I've been having problems interpreting the results produced by smc2arg, and I find that's because the tip label numbers seem to be ignored (or are invisibly reassigned) in the .arg output file. A trivial example is the following .smc file, which groups tips 3 and 0 most closely together:

```
NAMES	0	2	3	1
REGION	chr	1	10000
TREE	1	10000	(2:5363.846221[&&NHX:age=0.000000],(1:1002.805899[&&NHX:age=0.000000],(3:639.178343[&&NHX:age=0.000000],0:639.178343[&&NHX:age=0.000000])6:363.627557[&&NHX:age=639.178343])5:4361.040322[&&NHX:age=1002.805899])4[&&NHX:age=5363.846221];
```

when run through smc2arg, I find that it produces the following .arg file

```
start=0	end=10000
name	event	age	pos	parents	children
4	coal	5363.846221	0		3,5
5	coal	1002.805899	0	4	2,6
6	coal	639.178343	0	5	1,0
1	gene	0.0	0	6	
0	gene	0.0	0	6	
3	gene	0.0	0	4	
2	gene	0.0	0	5	
```

In which the two most tightly grouped tips are clearly 0 and 1. It seems like smc2arg has relabelled 2->3, 1->2, 3->0, and 0->1, otherwise I can't see how this arg file corresponds to the equivalent .smc file. Indeed, if I run the .arg file through arg2trees, it produces a tree which disagrees with the SMC file:

```
0	10000	(3:5363.846221,(2:1002.805899,(0:639.178343,1:639.178343):363.627556):4361.040322);
```

**Comment by hyanwong** [comment]
~~~This may also explain the previous issue I reported: https://github.com/mdrasmus/argweaver/issues/19~~~

**Comment by swamidass** [comment]
Seems like development has shifted to: https://github.com/mjhubisz/argweaver/commits/master

Perhaps post your bug there.

**Comment by hyanwong** [comment]
Ah - thanks for pointing that out. Very useful, thanks.

**Comment by mjhubisz** [comment]
This is not exactly a bug, but a confusion of the SMC file format. SMC files always contain trees with tips labeled 0..(n-1), those labels correspond to the order that the leaf names are given on the NAMES line at the top of the file. It gets very confusing when the leaf names are also those same integers. I would recommend using a string for your leaf names, it will make much more sense.
Once you run smc2arg, you are getting back the original leaf names. You may want to look at the format documentation for SMC and ARG files here: http://mdrasmus.github.io/argweaver/doc/

**Comment by hyanwong** [comment]
@mjhubisz thanks a lot for correcting my confusion. I'll close this, but I don't think this can therefore be the explanation for #19.

**Comment by hyanwong** [comment]
@mjhubisz I think one of the confusing things is that smc2arg does not seem to preserve the names in the ARG file that is output, but just uses the 0-based number system introduced in the SMC file. That means there is no way to work out the original tips purely from the ARG file.
