### ISSUE TITLE
Trying to get it to work - Crash on Data Load

### ISSUE THREAD

**Issue by ThaddeusAid** [mdrasmus/argweaver#8]
I really enjoyed your paper and I am trying to get ARGweaver working. I think I have managed to translate my IMPUTE datafile (translated from 1000 Genomes VCF file, is there a direct utility that will pull my data from the 1000G data vcfs?)

Sample of .sites file

aid@smew $ head ceu-chr2-sub.sites
NAMES   NA06984-A       NA06984-B       NA06986-A       NA06986-B       NA06989-A       NA06989-B       NA06994-A       NA06994-B       NA07000-A       NA07000-B       NA07037-A       NA07037-B       NA07048-A       NA07048-B       NA07056-A       NA07056-B       NA10851-A       NA10851-B       NA11892-A       NA11892-B       NA11930-A       NA11930-B       NA11933-A       NA11933-B       NA11992-A       NA11992-B       NA11993-A       NA11993-B       NA11994-A       NA11994-B       NA12003-A       NA12003-B       NA12004-A       NA12004-B       NA12006-A       NA12006-B       NA12043-A       NA12043-B       NA12045-A       NA12045-B       NA12058-A       NA12058-B       NA12144-A       NA12144-B       NA12154-A       NA12154-B       NA12249-A       NA12249-B       NA12272-A       NA12272-B       NA12275-A       NA12275-B       NA12283-A       NA12283-B       NA12286-A       NA12286-B       NA12287-A       NA12287-B       NA12347-A       NA12347-B       NA12348-A       NA12348-B       NA12383-A       NA12383-B       NA12399-A       NA12399-B       NA12400-A       NA12400-B       NA12413-A       NA12413-B       NA12489-A       NA12489-B       NA12716-A       NA12716-B       NA12717-A       NA12717-B       NA12718-A       NA12718-B       NA12750-A       NA12750-B       NA12751-A       NA12751-B       NA12775-A       NA12775-B       NA12777-A       NA12777-B       NA12778-A       NA12778-B       NA12815-A       NA12815-B       NA12842-A       NA12842-B       NA12872-A       NA12872-B       NA12873-A       NA12873-B       NA12889-A       NA12889-B       NA12890-A       NA12890-B
REGION  2       1       243188919
10133   CCCACCCACCCACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCACCCCCCCCCCCCCCCCCACCCCCCCCCCCCCACCCCCCCCCACC
10286   TTTTTTTTTTTTTTTATTTTTTTTTTTTTATATTTTATTTTTTTTTTTTTTTTTTTTTATTAATTATTTTTTTTTTTTTTTTTTTTTATTATTTATATTT
10297   GGGTGGTGGGGGGGGTGGGGGGGTGTTGGGGTGTGGGGGGGGGGGGGGGGGGGTTGGGGGGTGGGGGGGGGTGGTGGGGGGGGGGGGGGGTGGGGGGGTG
10345   GGGAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
10386   GGGTGGTGGGGTGGGGGGGGGGGGTGGGGGGTGGGGGGGGGGGGGGGGGGGGGGTGGGGGGGGGGGGGGGGGGGGGGGGGTGGGGGGGTGGGTGGGGGTG
10419   CCCCCGGCGGCCCCCCCGCCCGGCCCGCGCCGCCCCCCCCCCCCCGCCCCCCGCGCCCCGCCCGCCCCGCCCCCCCCCCGCCCCCCCCGCGGCCGCGCCC
10425   CCCCCCGCCCCCCCCCCGCCCCGCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGCCCCGCCCCCCCCGCCCCCCCCCCCCCCCCCCCGCCCCCCCCCCC
10431   CCCTCCCCCCCCCCCCCCCCCCCTCCCCCCCCCCCCCCCCCCCCCCCCCCCCCTTCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCTC
aid@smew $

But when I try and execute I get the following error

aid@smew $ arg-sample     -s ceu-chr2-sub.sites     -N 10000 -r 1.6e-8 -m 1.8e-8     --ntimes 20 --maxtime 200e3 -c 10 -n 500     -o arg-1/ceu-chr2-1 --region 134988584-135988584
arg-sample 0.8
start time: Fri May 30 16:49:23 2014
command: arg-sample -s ceu-chr2-sub.sites -N 10000 -r 1.6e-8 -m 1.8e-8 --ntimes 20 --maxtime 200e3 -c 10 -n 500 -o arg-1/ceu-chr2-1 --region 134988584-135988584
random seed: 1401464963
read input sites (chrom=2, start=134988583, end=135988584, length=1000001, nseqs=100, nsites=3144)
arg-sample: src/sequences.cpp:409: bool argweaver::find_compress_cols(const argweaver::Sites*, int, argweaver::SitesMapping*): Assertion `sites_mapping->all_sites[n-1] != sites_mapping->all_sites[n-2]' failed.
Aborted (core dumped)

Any illumination you could provide would be greatly appreciated!

**Comment by jessicahr** [comment]
I would like to know how to transform a VCF to .sites file. I'm trying to use the newer version of ARGweaver and it doesn't accept VCF as input. Could you please help me find a way to extract that information from my VCF.
Thank you in advance!!
